In [ ]:
import pandas as pd

# 1. Membaca dataset
print("===== 1. Membaca Dataset =====")
df = pd.read_csv('gym_membership.csv')
print(f"Jumlah total data: {len(df)} baris\n")







# 5. Menampilkan jumlah data yang kosong
print("===== 5. Jumlah Data Kosong per Kolom =====")
null_counts = df.isnull().sum()
for column, count in null_counts.items():
    print(f"{column}: {count} data kosong")
print("\n")

# 6. Analisis berdasarkan kategori umur
print("===== 6. Analisis Berdasarkan Kategori Umur =====")
# Membuat kategori umur
df['age_category'] = df['Age'].apply(lambda x: '1-18 tahun' if x <= 18 else '18+ tahun')

# Statistik per kategori umur
age_stats = df.groupby('age_category').agg({
    'id': 'count',
    'avg_time_in_gym': ['mean', 'min', 'max']
}).round(2)

print("Statistik per kategori umur:")
for category in age_stats.index:
    print(f"\nKategori: {category}")
    print(f"Jumlah member: {age_stats.loc[category, ('id', 'count')]} orang")
    print(f"Rata-rata waktu: {age_stats.loc[category, ('avg_time_in_gym', 'mean')]} menit")
    print(f"Waktu minimum: {age_stats.loc[category, ('avg_time_in_gym', 'min')]} menit")
    print(f"Waktu maksimum: {age_stats.loc[category, ('avg_time_in_gym', 'max')]} menit")

# Statistik per kategori umur dan gender
print("\nStatistik per kategori umur dan gender:")
age_gender_stats = df.groupby(['age_category', 'gender'])['avg_time_in_gym'].agg(['count', 'mean', 'min', 'max']).round(2)
print(age_gender_stats)

===== 1. Membaca Dataset =====
Jumlah total data: 1000 baris

===== 2. Deskripsi Data =====
                id          Age  visit_per_week  avg_time_in_gym
count  1000.000000  1000.000000     1000.000000      1000.000000
mean    500.500000    30.604000        2.682000       105.260000
std     288.819436    10.817958        1.241941        43.557177
min       1.000000    12.000000        1.000000        30.000000
25%     250.750000    21.000000        2.000000        67.000000
50%     500.500000    30.000000        3.000000       104.000000
75%     750.250000    40.000000        3.000000       143.000000
max    1000.000000    49.000000        5.000000       180.000000

Informasi kolom:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     1000 non-null   int64
 1   gender                 1000 non-null   object
 2   birthday               1000 non-null   object
 3   Age                    1000 non-null   int64
 4   abonoment_type         1000 non-null   object
 5   visit_per_week         1000 non-null   int64
 6   days_per_week          1000 non-null   object
 7   attend_group_lesson    1000 non-null   bool
 8   fav_group_lesson       503 non-null    object
 9   avg_time_check_in      1000 non-null   object
 10  avg_time_check_out     1000 non-null   object
 11  avg_time_in_gym        1000 non-null   int64
 12  drink_abo              1000 non-null   bool
 13  fav_drink              496 non-null    object
 14  personal_training      1000 non-null   bool
 15  name_personal_trainer  518 non-null    object
 16  uses_sauna             1000 non-null   bool
dtypes: bool(4), int64(4), object(9)
memory usage: 105.6+ KB
None


===== 3. 10 Data Pertama =====

Member ke-1:
Umur: 27 tahun
Gender: Female
Tipe Membership: Premium
Waktu Check-in: 19:31:00
Waktu Check-out: 21:27:00
Total Waktu di Gym: 116 menit

Member ke-2:
Umur: 47 tahun
Gender: Female
Tipe Membership: Standard
Waktu Check-in: 19:31:00
Waktu Check-out: 20:19:00
Total Waktu di Gym: 48 menit

Member ke-3:
Umur: 41 tahun
Gender: Male
Tipe Membership: Premium
Waktu Check-in: 08:29:00
Waktu Check-out: 10:32:00
Total Waktu di Gym: 123 menit

Member ke-4:
Umur: 44 tahun
Gender: Male
Tipe Membership: Premium
Waktu Check-in: 09:54:00
Waktu Check-out: 11:33:00
Total Waktu di Gym: 99 menit

Member ke-5:
Umur: 44 tahun
Gender: Male
Tipe Membership: Standard
Waktu Check-in: 08:29:00
Waktu Check-out: 09:19:00
Total Waktu di Gym: 50 menit

Member ke-6:
Umur: 15 tahun
Gender: Female
Tipe Membership: Standard
Waktu Check-in: 17:19:00
Waktu Check-out: 20:19:00
Total Waktu di Gym: 180 menit

Member ke-7:
Umur: 30 tahun
Gender: Male
Tipe Membership: Premium
Waktu Check-in: 19:46:00
Waktu Check-out: 20:48:00
Total Waktu di Gym: 62 menit

Member ke-8:
Umur: 20 tahun
Gender: Male
Tipe Membership: Standard
Waktu Check-in: 17:45:00
Waktu Check-out: 19:20:00
Total Waktu di Gym: 95 menit

Member ke-9:
Umur: 46 tahun
Gender: Male
Tipe Membership: Premium
Waktu Check-in: 09:45:00
Waktu Check-out: 11:17:00
Total Waktu di Gym: 92 menit

Member ke-10:
Umur: 24 tahun
Gender: Female
Tipe Membership: Premium
Waktu Check-in: 13:05:00
Waktu Check-out: 15:29:00
Total Waktu di Gym: 144 menit


===== 4. Data Terurut Berdasarkan Waktu di Gym (Top 10) =====

Peringkat 1:
ID: 6
Umur: 15 tahun
Gender: Female
Waktu di Gym: 180 menit

Peringkat 2:
ID: 568
Umur: 35 tahun
Gender: Female
Waktu di Gym: 180 menit

Peringkat 3:
ID: 488
Umur: 43 tahun
Gender: Male
Waktu di Gym: 180 menit

Peringkat 4:
ID: 442
Umur: 30 tahun
Gender: Female
Waktu di Gym: 180 menit

Peringkat 5:
ID: 427
Umur: 14 tahun
Gender: Male
Waktu di Gym: 180 menit

Peringkat 6:
ID: 382
Umur: 45 tahun
Gender: Male
Waktu di Gym: 180 menit

Peringkat 7:
ID: 79
Umur: 43 tahun
Gender: Female
Waktu di Gym: 180 menit

Peringkat 8:
ID: 735
Umur: 33 tahun
Gender: Female
Waktu di Gym: 180 menit

Peringkat 9:
ID: 238
Umur: 21 tahun
Gender: Female
Waktu di Gym: 179 menit

Peringkat 10:
ID: 819
Umur: 20 tahun
Gender: Female
Waktu di Gym: 179 menit


===== 5. Jumlah Data Kosong per Kolom =====
id: 0 data kosong
gender: 0 data kosong
birthday: 0 data kosong
Age: 0 data kosong
abonoment_type: 0 data kosong
visit_per_week: 0 data kosong
days_per_week: 0 data kosong
attend_group_lesson: 0 data kosong
fav_group_lesson: 497 data kosong
avg_time_check_in: 0 data kosong
avg_time_check_out: 0 data kosong
avg_time_in_gym: 0 data kosong
drink_abo: 0 data kosong
fav_drink: 504 data kosong
personal_training: 0 data kosong
name_personal_trainer: 482 data kosong
uses_sauna: 0 data kosong


===== 6. Analisis Berdasarkan Kategori Umur =====
Statistik per kategori umur:

Kategori: 1-18 tahun
Jumlah member: 171 orang
Rata-rata waktu: 107.9 menit
Waktu minimum: 30 menit
Waktu maksimum: 180 menit

Kategori: 18+ tahun
Jumlah member: 829 orang
Rata-rata waktu: 104.72 menit
Waktu minimum: 30 menit
Waktu maksimum: 180 menit

Statistik per kategori umur dan gender:
                     count    mean  min  max
age_category gender
1-18 tahun   Female     91  107.81   31  180
             Male       80  108.00   30  180
18+ tahun    Female    412  105.95   30  180
             Male      417  103.50   30  180

In [ ]:
# 4. Mengurutkan dan menampilkan data
print("===== 4. Data Terurut Berdasarkan Waktu di Gym (Top 10) =====")
sorted_df = df.sort_values('avg_time_in_gym', ascending=False).head(10)
for idx, row in sorted_df.iterrows():
    print(f"\nPeringkat {sorted_df.index.get_loc(idx) + 1}:")
    print(f"ID: {row['id']}")
    print(f"Umur: {row['Age']} tahun")
    print(f"Gender: {row['gender']}")
    print(f"Waktu di Gym: {row['avg_time_in_gym']} menit")
print("\n")

In [ ]:
# 3. Menampilkan 10 data pertama menggunakan iterrows
print("===== 3. 10 Data Pertama =====")
for idx, row in df.head(10).iterrows():
    print(f"\nMember ke-{idx + 1}:")
    print(f"Umur: {row['Age']} tahun")
    print(f"Gender: {row['gender']}")
    print(f"Tipe Membership: {row['abonoment_type']}")
    print(f"Waktu Check-in: {row['avg_time_check_in']}")
    print(f"Waktu Check-out: {row['avg_time_check_out']}")
    print(f"Total Waktu di Gym: {row['avg_time_in_gym']} menit")
print("\n")

In [ ]:
# 2. Menampilkan deskripsi data
print("===== 2. Deskripsi Data =====")
print(df.describe())
print("\nInformasi kolom:")
print(df.info())
print("\n")

In [13]:
# 2. Menampilkan deskripsi data
print("Deskripsi Data:")
gymDF.describe()


# 3. Menampilkan 10 data pertama menggunakan iterrows
print("10 Data Pertama:")
for index, row in gymDF.head(10).iterrows():
    print(row)

# 4. Mengurutkan data berdasarkan umur (Age)
gymDF = gymDF.sort_values(by='Age')
print("Data yang Sudah Diurutkan Berdasarkan Umur:")
gymDF.head()

# 5. Menampilkan jumlah data yang kosong
print("Jumlah Data yang Kosong:")
print(gymDF.isnull().sum())
print()

Deskripsi Data:
10 Data Pertama:
id                                                1
gender                                       Female
birthday                                 1997-04-18
Age                                              27
abonoment_type                              Premium
visit_per_week                                    4
days_per_week                    Mon, Sat, Tue, Wed
attend_group_lesson                            True
fav_group_lesson         Kickboxen, BodyPump, Zumba
avg_time_check_in                          19:31:00
avg_time_check_out                         21:27:00
avg_time_in_gym                                 116
drink_abo                                     False
fav_drink                                       NaN
personal_training                             False
name_personal_trainer                           NaN
uses_sauna                                     True
Name: 0, dtype: object
id                                   2
gender                          Female
birthday                    1977-09-18
Age                                 47
abonoment_type                Standard
visit_per_week                       3
days_per_week            Mon, Sat, Wed
attend_group_lesson              False
fav_group_lesson                   NaN
avg_time_check_in             19:31:00
avg_time_check_out            20:19:00
avg_time_in_gym                     48
drink_abo                        False
fav_drink                          NaN
personal_training                 True
name_personal_trainer          Chantal
uses_sauna                       False
Name: 1, dtype: object
id                                        3
gender                                 Male
birthday                         1983-03-30
Age                                      41
abonoment_type                      Premium
visit_per_week                            1
days_per_week                           Sat
attend_group_lesson                    True
fav_group_lesson                      XCore
avg_time_check_in                  08:29:00
avg_time_check_out                 10:32:00
avg_time_in_gym                         123
drink_abo                              True
fav_drink                berry_boost, lemon
personal_training                      True
name_personal_trainer                  Mike
uses_sauna                            False
Name: 2, dtype: object
id                                   4
gender                            Male
birthday                    1980-04-12
Age                                 44
abonoment_type                 Premium
visit_per_week                       3
days_per_week            Sat, Tue, Wed
attend_group_lesson              False
fav_group_lesson                   NaN
avg_time_check_in             09:54:00
avg_time_check_out            11:33:00
avg_time_in_gym                     99
drink_abo                         True
fav_drink                passion_fruit
personal_training                 True
name_personal_trainer             Mike
uses_sauna                        True
Name: 3, dtype: object
id                                          5
gender                                   Male
birthday                           1980-09-10
Age                                        44
abonoment_type                       Standard
visit_per_week                              2
days_per_week                        Thu, Wed
attend_group_lesson                      True
fav_group_lesson         Running, Yoga, Zumba
avg_time_check_in                    08:29:00
avg_time_check_out                   09:19:00
avg_time_in_gym                            50
drink_abo                               False
fav_drink                                 NaN
personal_training                        True
name_personal_trainer                    Mike
uses_sauna                              False
Name: 4, dtype: object
id                                6
gender                       Female
birthday                 2009-06-29
Age                              15
abonoment_type             Standard
visit_per_week                    1
days_per_week                   Mon
attend_group_lesson           False
fav_group_lesson                NaN
avg_time_check_in          17:19:00
avg_time_check_out         20:19:00
avg_time_in_gym                 180
drink_abo                     False
fav_drink                       NaN
personal_training             False
name_personal_trainer           NaN
uses_sauna                     True
Name: 5, dtype: object
id                                        7
gender                                 Male
birthday                         1994-08-07
Age                                      30
abonoment_type                      Premium
visit_per_week                            3
days_per_week                 Sat, Thu, Wed
attend_group_lesson                    True
fav_group_lesson         LesMiles, BodyPump
avg_time_check_in                  19:46:00
avg_time_check_out                 20:48:00
avg_time_in_gym                          62
drink_abo                             False
fav_drink                               NaN
personal_training                     False
name_personal_trainer                   NaN
uses_sauna                            False
Name: 6, dtype: object
id                                       8
gender                                Male
birthday                        2003-11-13
Age                                     20
abonoment_type                    Standard
visit_per_week                           2
days_per_week                     Mon, Wed
attend_group_lesson                   True
fav_group_lesson               Yoga, XCore
avg_time_check_in                 17:45:00
avg_time_check_out                19:20:00
avg_time_in_gym                         95
drink_abo                             True
fav_drink                coconut_pineapple
personal_training                    False
name_personal_trainer                  NaN
uses_sauna                            True
Name: 7, dtype: object
id                                   9
gender                            Male
birthday                    1978-07-28
Age                                 46
abonoment_type                 Premium
visit_per_week                       3
days_per_week            Sat, Sun, Thu
attend_group_lesson               True
fav_group_lesson              BodyPump
avg_time_check_in             09:45:00
avg_time_check_out            11:17:00
avg_time_in_gym                     92
drink_abo                         True
fav_drink                orange, lemon
personal_training                 True
name_personal_trainer             Mike
uses_sauna                       False
Name: 8, dtype: object
id                               10
gender                       Female
birthday                 2000-05-06
Age                              24
abonoment_type              Premium
visit_per_week                    1
days_per_week                   Mon
attend_group_lesson           False
fav_group_lesson                NaN
avg_time_check_in          13:05:00
avg_time_check_out         15:29:00
avg_time_in_gym                 144
drink_abo                     False
fav_drink                       NaN
personal_training              True
name_personal_trainer       Jeffrey
uses_sauna                     True
Name: 9, dtype: object
Data yang Sudah Diurutkan Berdasarkan Umur:
Jumlah Data yang Kosong:
id                         0
gender                     0
birthday                   0
Age                        0
abonoment_type             0
visit_per_week             0
days_per_week              0
attend_group_lesson        0
fav_group_lesson         497
avg_time_check_in          0
avg_time_check_out         0
avg_time_in_gym            0
drink_abo                  0
fav_drink                504
personal_training          0
name_personal_trainer    482
uses_sauna                 0
dtype: int64

===== 1. Membaca Dataset =====
Jumlah total data: 1000 baris

===== 2. Deskripsi Data =====
                id          Age  visit_per_week  avg_time_in_gym
count  1000.000000  1000.000000     1000.000000      1000.000000
mean    500.500000    30.604000        2.682000       105.260000
std     288.819436    10.817958        1.241941        43.557177
min       1.000000    12.000000        1.000000        30.000000
25%     250.750000    21.000000        2.000000        67.000000
50%     500.500000    30.000000        3.000000       104.000000
75%     750.250000    40.000000        3.000000       143.000000
max    1000.000000    49.000000        5.000000       180.000000

Informasi kolom:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     1000 non-null   int64
 1   gender                 1000 non-null   object
 2   birthday               1000 non-null   object
 3   Age                    1000 non-null   int64
 4   abonoment_type         1000 non-null   object
 5   visit_per_week         1000 non-null   int64
 6   days_per_week          1000 non-null   object
 7   attend_group_lesson    1000 non-null   bool
 8   fav_group_lesson       503 non-null    object
 9   avg_time_check_in      1000 non-null   object
 10  avg_time_check_out     1000 non-null   object
 11  avg_time_in_gym        1000 non-null   int64
 12  drink_abo              1000 non-null   bool
 13  fav_drink              496 non-null    object
 14  personal_training      1000 non-null   bool
 15  name_personal_trainer  518 non-null    object
 16  uses_sauna             1000 non-null   bool
dtypes: bool(4), int64(4), object(9)
memory usage: 105.6+ KB
None


===== 3. 10 Data Pertama =====

Member ke-1:
Umur: 27 tahun
Gender: Female
Tipe Membership: Premium
Waktu Check-in: 19:31:00
Waktu Check-out: 21:27:00
Total Waktu di Gym: 116 menit

Member ke-2:
Umur: 47 tahun
Gender: Female
Tipe Membership: Standard
Waktu Check-in: 19:31:00
Waktu Check-out: 20:19:00
Total Waktu di Gym: 48 menit

Member ke-3:
Umur: 41 tahun
Gender: Male
Tipe Membership: Premium
Waktu Check-in: 08:29:00
Waktu Check-out: 10:32:00
Total Waktu di Gym: 123 menit

Member ke-4:
Umur: 44 tahun
Gender: Male
Tipe Membership: Premium
Waktu Check-in: 09:54:00
Waktu Check-out: 11:33:00
Total Waktu di Gym: 99 menit

Member ke-5:
Umur: 44 tahun
Gender: Male
Tipe Membership: Standard
Waktu Check-in: 08:29:00
Waktu Check-out: 09:19:00
Total Waktu di Gym: 50 menit

Member ke-6:
Umur: 15 tahun
Gender: Female
Tipe Membership: Standard
Waktu Check-in: 17:19:00
Waktu Check-out: 20:19:00
Total Waktu di Gym: 180 menit

Member ke-7:
Umur: 30 tahun
Gender: Male
Tipe Membership: Premium
Waktu Check-in: 19:46:00
Waktu Check-out: 20:48:00
Total Waktu di Gym: 62 menit

Member ke-8:
Umur: 20 tahun
Gender: Male
Tipe Membership: Standard
Waktu Check-in: 17:45:00
Waktu Check-out: 19:20:00
Total Waktu di Gym: 95 menit

Member ke-9:
Umur: 46 tahun
Gender: Male
Tipe Membership: Premium
Waktu Check-in: 09:45:00
Waktu Check-out: 11:17:00
Total Waktu di Gym: 92 menit

Member ke-10:
Umur: 24 tahun
Gender: Female
Tipe Membership: Premium
Waktu Check-in: 13:05:00
Waktu Check-out: 15:29:00
Total Waktu di Gym: 144 menit


===== 4. Data Terurut Berdasarkan Waktu di Gym (Top 10) =====

Peringkat 1:
ID: 6
Umur: 15 tahun
Gender: Female
Waktu di Gym: 180 menit

Peringkat 2:
ID: 568
Umur: 35 tahun
Gender: Female
Waktu di Gym: 180 menit

Peringkat 3:
ID: 488
Umur: 43 tahun
Gender: Male
Waktu di Gym: 180 menit

Peringkat 4:
ID: 442
Umur: 30 tahun
Gender: Female
Waktu di Gym: 180 menit

Peringkat 5:
ID: 427
Umur: 14 tahun
Gender: Male
Waktu di Gym: 180 menit

Peringkat 6:
ID: 382
Umur: 45 tahun
Gender: Male
Waktu di Gym: 180 menit

Peringkat 7:
ID: 79
Umur: 43 tahun
Gender: Female
Waktu di Gym: 180 menit

Peringkat 8:
ID: 735
Umur: 33 tahun
Gender: Female
Waktu di Gym: 180 menit

Peringkat 9:
ID: 238
Umur: 21 tahun
Gender: Female
Waktu di Gym: 179 menit

Peringkat 10:
ID: 819
Umur: 20 tahun
Gender: Female
Waktu di Gym: 179 menit


===== 5. Jumlah Data Kosong per Kolom =====
id: 0 data kosong
gender: 0 data kosong
birthday: 0 data kosong
Age: 0 data kosong
abonoment_type: 0 data kosong
visit_per_week: 0 data kosong
days_per_week: 0 data kosong
attend_group_lesson: 0 data kosong
fav_group_lesson: 497 data kosong
avg_time_check_in: 0 data kosong
avg_time_check_out: 0 data kosong
avg_time_in_gym: 0 data kosong
drink_abo: 0 data kosong
fav_drink: 504 data kosong
personal_training: 0 data kosong
name_personal_trainer: 482 data kosong
uses_sauna: 0 data kosong


===== 6. Analisis Berdasarkan Kategori Umur =====
Statistik per kategori umur:

Kategori: 1-18 tahun
Jumlah member: 171 orang
Rata-rata waktu: 107.9 menit
Waktu minimum: 30 menit
Waktu maksimum: 180 menit

Kategori: 18+ tahun
Jumlah member: 829 orang
Rata-rata waktu: 104.72 menit
Waktu minimum: 30 menit
Waktu maksimum: 180 menit

Statistik per kategori umur dan gender:
                     count    mean  min  max
age_category gender
1-18 tahun   Female     91  107.81   31  180
             Male       80  108.00   30  180
18+ tahun    Female    412  105.95   30  180
             Male      417  103.50   30  180

In [11]:
gymDF.duplicated().sum()

np.int64(0)

In [ ]:
gymDF['avg_time_check_in'] = pd.to_timedelta(gymDF['avg_time_check_in'])
gymDF['avg_time_check_out'] = pd.to_timedelta(gymDF['avg_time_check_out'])